### ISSUE TITLE
rake db:setup fails after cloning the repository

### ISSUE THREAD

**Issue by aitbw** [aitbw/af_maracay#3]
If you try to execute the `rake db:setup` command after cloning the repository and creating the 'database.yml' file under config/, it will throw a 'rake aborted' error with the following stack trace:

```
rake aborted!
NameError: uninitialized constant Payment::PaymentStatuses
/home/aitbw/test/af_maracay/models/payments_model.rb:20:in `<class:Payment>'
/home/aitbw/test/af_maracay/models/payments_model.rb:18:in `<top (required)>'
/home/aitbw/test/af_maracay/app.rb:6:in `block in <top (required)>'
/home/aitbw/test/af_maracay/app.rb:5:in `each'
/home/aitbw/test/af_maracay/app.rb:5:in `<top (required)>'
/home/aitbw/test/af_maracay/Rakefile:7:in `block (2 levels) in <top (required)>'
/home/aitbw/.rvm/gems/ruby-2.3.0@af_maracay/bin/ruby_executable_hooks:15:in `eval'
/home/aitbw/.rvm/gems/ruby-2.3.0@af_maracay/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:setup => db:schema:load_if_ruby => db:create => db:load_config
(See full trace by running task with --trace)
```

The stack trace reveals this occurs because the PaymentStatuses (see [payment_statuses.rb](https://github.com/aitbw/af_maracay/blob/master/models/concerns/payment_statuses.rb)) module wasn't loaded properly, which is weird considering line 5 under [app.rb](https://github.com/aitbw/af_maracay/blob/master/app.rb#L5) **should load** all the app's files.

I must note as well that this had happened under Ubuntu 16.04 **and** Xubuntu 14.04, but not under Manjaro Gnome 16.06.
### Workaround

The quick fix to this issue is to add the following line: `require './models/concerns/payment_statuses.rb'` at the top of [payments_model.rb](https://github.com/aitbw/af_maracay/blob/master/models/payments_model.rb), but this should be addressed on a short term to avoid inconveniences with any developer who might want to try this app or expand its features.

**Comment by leocabeza** [comment]
This is also related:

After cloning the project and executing `rake db:setup` I get the error:

```
postgres already exists
-- enable_extension("plpgsql")
   -> 0.0204s
-- enable_extension("hstore")
rake aborted!
ActiveRecord::StatementInvalid: PG::UndefinedFile: ERROR:  could not open extension control file "/usr/share/postgresql/9.4/extension/hstore.control": No such file or directory
```

### Workaround

instead of installing

`postgresql postgresql-contrib postgresql-server-dev-9.5`

it should be

`postgresql postgresql-contrib-9.4 postgresql-server-dev-9.5`

**Comment by aitbw** [comment]
Never had any issues with installing PG as stated on the README, @leocabeza, but I think your issue could be related with `postgresql-contrib` and `postgresql-server-dev` versions.

Maybe it would be nice to add to the instructions to specify the versions you want to install for the aforementioned packages.
